### PR TITLE
Add Nix lexer

### LINKED ISSUE #116: Add a nix Lexer
It would be nice to have an lexer for nix files (used by NixOS/nix package manager)

### PR DESCRIPTION
**Pull request by techee**
This PR adds the Nix lexer which I based on the recenly merged Dart lexer. Some of the language details can be found in

https://nix.dev/manual/nix/2.24/language/syntax

and related documents.

Some notes about the implementation:
1. For key detection (`key = value;`) I used the same lookahead technique as used in the JSON lexer which tries to find `=` after the identifier.
2. I used something similar for path literals (https://nix.dev/manual/nix/2.24/language/syntax#path-literal) which are kind of vaguely defined and based on the fact that there is `/` somewhere inside the literal. It didn't seem to be a problem for sources I used for testing but searching for `/` in every identifier might cause performance issues - if it is a problem, path literal highlighting could be performed only for `<paths_in_braces>`.

There's one issue I'm aware of - folding of sources like
```nix
{
  # stuff
} ''
multi line string
''
```
where the end of the block `}` is on the same line like the start of multiline string `''`. This style is used e.g. in

https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/docker/default.nix

and I added an example of this at the end of the unit test. What happens is that fold level is unchanged on the `} ''` line because it is decreased and increased at the same time so the result is that folding starts at the initial `{` and ends at the final `''` which is strange. It would be OK if it were just a combination of the same blocks like
```
{
} {
}
```
but it's strange when it's block+string. Do any other lexers have to solve this issue and what is the recommended approach here? One way would be to completely disable folding of multiline strings or just accept this behavior if there's no better option.

Fixes #116.

### CODE REVIEW

**Comment by rdipardo** [comment]
> Do any other lexers have to solve this issue and what is the recommended approach here? 

The Lua lexer appears to manage it,  probably because multi line strings [preserve line state](https://github.com/ScintillaOrg/lexilla/blob/0784d05075bd85cf151c480c08537716ec11f70e/lexers/LexLua.cxx#L292-L294).

<div align="center">scite-552-lua-folded</div>

**Comment by techee** [comment]
Oh and by the way, how did you get that line state information to the left margin?

**Comment by nyamatongwe** [comment]
> but it's strange when it's block+string. Do any other lexers have to solve this issue and what is the recommended approach here? 

Lexers just accept this. It is similar to folding an if/else structure in 2 places which is a common idiom that uses the `fold.at.else` property. This was initially implemented in the `cpp` lexer so that should be examined.
~~~c++
if () {
	;
} else { // Fold here?
	;
}
~~~
This is why many lexers store 2 fold level numbers per line: a level to base folding on and the start level for the next line in high bits that are ignored for fold interaction.
~~~c++
int lev = levelUse | levelNext << 16;
~~~

> Oh and by the way, how did you get that line state information to the left margin?

~~~c++
SCI_SETFOLDFLAGS(SC_FOLDFLAG_LEVELNUMBERS)
// or, in SciTE properties
fold.flags=64
~~~

**Comment by techee** [comment]
> Lexers just accept this.

OK, so if it's not a big problem, I'd just leave it as it is.

**Comment by nyamatongwe** [comment]
SciTE is a separate project with a feature request tracker at https://sourceforge.net/p/scintilla/feature-requests/ . New languages have a new `.properties` file and are commonly excluded (to limit UI element length) by being added to `imports.exclude` in `scite/src/SciTEGlobal.properties`.

Lexers are often contributed by people working on other applications so don't always come with a SciTE `.properties` file.

Look into some of the other settings files like `python.properties` to see how style numbers are converted to distinct visuals.

**Comment by AntiSol** [comment]
@nyamatongwe thanks very much, this was just the hint I needed to figure it out.

I just might turn up on sourceforge with a nix.properties file for you

Thanks for SciTE and scintilla btw, it should be a testament to the quality of your work that I've been using them for 20+ years and this is the first time we've spoken

**Pull request closed without merging**
