### PR TITLE
Fix lexing of nested comments; remove unused variable

### PR DESCRIPTION
**Pull request by mgusg**
Fix a bug which caused improper lexing of nested block comments.
Add a regression test for block comments and single-line comments.
Remove unused variable visibleChars in LexerABL::Lex.

### CODE REVIEW

**Comment by nyamatongwe** [comment]
The test requires a `SciTE.properties` file in the same directory to specify the lexer to test and turn on folding. Something similar to
~~~text
lexer.*.p=abl
fold=1
~~~

Removing `visibleChars` means that the local function `IsSpaceEquiv` is no longer called and should be removed to avoid warnings.
~~~text
../lexers/LexProgress.cxx:51:9: warning: 'bool {anonymous}::IsSpaceEquiv(int)' defined but not used [-Wunused-function]
   51 |    bool IsSpaceEquiv(int state) {
      |         ^~~~~~~~~~~~
~~~

[cppcheck](http://cppcheck.net/) shows a new warning for the look back loop. It may be possible to simplify this code.
~~~
lexilla\lexers\LexProgress.cxx:271:14: warning: Condition 'checkIsSentenceStart' is always true [knownConditionTrueFalse]
         if (checkIsSentenceStart && st != SCE_ABL_COMMENT && st != SCE_ABL_LINECOMMENT && st != SCE_ABL_CHARACTER  && st != SCE_ABL_STRING ) {
             ^
lexilla\lexers\LexProgress.cxx:264:27: note: Assuming that condition 'checkIsSentenceStart' is not redundant
      while (back >= 0 && checkIsSentenceStart) {
                          ^
lexilla\lexers\LexProgress.cxx:271:14: note: Condition 'checkIsSentenceStart' is always true
         if (checkIsSentenceStart && st != SCE_ABL_COMMENT && st != SCE_ABL_LINECOMMENT && st != SCE_ABL_CHARACTER  && st != SCE_ABL_STRING ) {
             ^
~~~

**Comment by mgusg** [comment]
Thanks for the feedback. I added the missing SciTE.properties file and resolved the issues reported by cppcheck.

**Comment by nyamatongwe** [comment]
In SciTE.properties you likely want the keyword 'DISPLAY' to be lowercase so that these are lexed to `SCE_ABL_WORD` (2) instead of `SCE_ABL_IDENTIFIER` (7). This lexer implements case-insensitive keywords by converting words to lowercase then searching in a list. This will never match 'DISPLAY'.

**Comment by mgusg** [comment]
I changed the keyword to lowercase and updated the .styled file. Thank you for the thorough review.

**Pull request closed without merging**
