### PR TITLE
Xml commentdoc keywords

### PR DESCRIPTION
**Pull request by stefankueng**
the cpp lexer is also used for e.g. C#, which usually uses XML styled comment doc keywords. This PR implements this.
Only the keywords are handled, no check for valid XML is done.

### CODE REVIEW

**Comment by nyamatongwe** [comment]
The choice of which surrounding characters are styled looks a bit strange. I'd be expecting just the keyword or keyword + both surrounding sequences. Perhaps there is a rationale for the implementation.
cppXmlDocKeywords

New features should have corresponding examples (and results in a .styled file) in test/examples/cpp either as additions to x.cpp or as a new file. That way, the testing framework may show regressions to that feature.
~~~c++
/** @file LexCPP.cxx
 <file>
 <file />
 <file/>
 LexCPP.cxx.
 </file>
 **/
~~~

**Comment by stefankueng** [comment]
changed so the brackets are not highlighted anymore, and added your example to the tests.

**Comment by nyamatongwe** [comment]
With this change, the specified keywords show as error doc keywords (18) instead of doc keywords (17).
cppXmlDocKeywords2

To see this, there should be a list of known keywords in the example's SciTE.properties like so:
~~~
keywords3.*.cxx=file
~~~

**Comment by nyamatongwe** [comment]
Committed the change.

Since there were some unwanted changes to whitespace I squashed the 6 commits into 1 as 5d0e78a65e4b0bf897f531836c398a758084a512.

Also added a test for unknown doc keywords with 1444b957b8d01a4010c11c902dc4a58b52deb1ec.

**Comment by stefankueng** [comment]
Thanks!
Closing this now.

**Comment by ajtruckle** [comment]
Hi Guys

Sorry to resurrect an old ticket. But I am new to Scintilla / Lexilla and I have need for displaying:

- XML
- XSL

I noticed that there was no specific XML lever available to use, so I came here to search the subject. And I located this issue that refers to using file type CPP. Is this still the case?

Thank you for confirming!

**Comment by nyamatongwe** [comment]
This issue is about `C#` and similar languages and their documentation comments.

**Pull request closed without merging**
