### PR TITLE
LexCPP: support 7th word list for colouring variables

### PR DESCRIPTION
**Pull request by eranif**

### CODE REVIEW

**Comment by nyamatongwe** [comment]
LexCPP supports an arbitrary number of identifier lists with [substyles](https://www.scintilla.org/ScintillaDoc.html#Substyles) which should be used here instead of using up a keyword list.

In SciTE the `substyles` and `substylewords` properties control this and other editors can examine SciTE's implementation of these properties as an example.
~~~
substyles.cpp.11=1
substylewords.11.1.$(file.patterns.cpp)=std map string vector
style.cpp.11.1=fore:#EE00AA
~~~

**Comment by eranif** [comment]
can this list be dynamic?
i.e. variables are something that are changes based on the file content

**Comment by nyamatongwe** [comment]
`SetIdentifiers` is the same as `SetKeyWords`: the list can be changed but then the whole file should be re-lexed. It does not support different lists for different scopes in the file.

**Comment by eranif** [comment]
Thanks, I wasn't looking for different scopes. For my purposes, the entire file is considered a single scope (its good enough)

**Comment by nyamatongwe** [comment]
Closing as rejecting use of 7th word list for colouring identifiers.

**Pull request closed without merging**
