### PR TITLE
#182 Restore cmdState after shell expansions.

### PR DESCRIPTION
**Pull request by zufuliu**

### CODE REVIEW

**Comment by zufuliu** [comment]
Fixed the test case (missing space before `]`).
It maybe better to add test case for arithmetic expansion optimization: `current == CmdState::Body && sc.Match('(', '(')`.

**Comment by zufuliu** [comment]
Test case for arithmetic expansion inside test command is added. dash in short/long command option no longer highlighted as operator.

**Comment by zufuliu** [comment]
Also I think it's better to move `IsAlpha()`, `IsIdentifierChar()` and `IsIdentifierStart()` from LexOScript.cxx to CharacterSet.h, many `IsASCII(ch) && isalpha(ch)` could be replaced with `IsAlpha(ch)`.

**Comment by nyamatongwe** [comment]
`IsAlpha` is available from `CharacterSet.h` with the name `IsUpperOrLowerCase`. `IsAlpha` is defined differently in `LexMagik.cxx`.

**Comment by zufuliu** [comment]
OK, replaced `IsAlpha()` with `IsUpperOrLowerCase()`.

**Comment by nyamatongwe** [comment]
Languages often allow a few punctuation characters like `-` and `%` in identifiers so I'm uncomfortable with pushing C's original `A-Za-z_` rule. Even for C, `$` is a popular extension which is supported by the `cpp` lexer.

So, I'd prefer a name that describes what it does (`IsAlphaOrUnder`?) for the header rather than describing its role. Lexers can add their own `IsIdentifierChar` or similar that can then be modified locally as needed.

**Pull request closed without merging**
