### PR TITLE
PowerShell: Remove backtick escape in single-quoted strings

### PR DESCRIPTION
**Pull request by xv**
Came across this issue of my syntax highlighting getting messed up and found the culprit to be the backtick character escaping in single-quoted strings, which is incorrect behavior.

From MSDN:

> Because the contents of single-quoted strings are interpreted literally, the backtick character is treated as a literal character and displayed in the output.
[Source](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.2#:~:text=Because%20the%20contents%20of%20single%2Dquoted%20strings%20are%20interpreted%20literally%2C%20the%20backtick%20character%20is%20treated%20as%20a%20literal%20character%20and%20displayed%20in%20the%20output.)

#### Current incorrect behaviour:

incorrect

#### Corrected behaviour in PR:

correct

### CODE REVIEW

**Comment by nyamatongwe** [comment]
This bug has also been reported as Scintilla[#2209](https://sourceforge.net/p/scintilla/bugs/2209/)

This behaviour stems from fixing bug [#1929](https://sourceforge.net/p/scintilla/bugs/1929/) with commit [6734b0](https://sourceforge.net/p/scintilla/code/ci/6734b0bc4328e4dc7f791a627d703d2e8d39c243/) which added backtick quotes for both string types.

**Comment by xv** [comment]
I have reviewed and tested commit [6734b0](https://sourceforge.net/p/scintilla/code/ci/6734b0bc4328e4dc7f791a627d703d2e8d39c243/). Escapes in double-quoted strings are correctly implemented; however, escapes in single-quoted strings _definitely_ shouldn't happen.

Also tested on PowerShell ISE:

ise

And VSCode:
vscode

**Comment by nyamatongwe** [comment]
Pushed https://github.com/ScintillaOrg/lexilla/commit/7758276e308af927647052a8a829604694da9133 which includes the code change and updates the test case a little.

The comments in the test case were converted to block comments `<# ... #>` because the lexer styles the `\r` and `\n` differently after line comments. This is a common problem in lexers and upsets the test runner - it is also a great source of bugs. The test case was also named after this issue `Pull92.ps1` as is convention for files that are illustrating a particular issue. Turned on folding in properties as its likely to be relevant in future issues.

**Comment by xv** [comment]
Looks great -- thank you for your time :)

**Pull request closed without merging**
