### PR TITLE
Adds a simple Asciidoc lexer

### PR DESCRIPTION
**Pull request by ancebfer**
Simple Asciidoc lexer following Asciidoctor recommended practiques:

https://asciidoctor.org/docs/asciidoc-recommended-practices/

Tested with Asciidoctor README.adoc file and SciTE:

https://github.com/asciidoctor/asciidoctor/blob/main/README.adoc

With this result:
scite

Using this "asciidoc.properties" for SciTE:
[asciidoc.properties.txt](https://github.com/ScintillaOrg/lexilla/files/7490923/asciidoc.properties.txt)

### CODE REVIEW

**Comment by nyamatongwe** [comment]
This is almost all good.

To prevent any possibility of clashes with other lexers, the `MacroItem` definition should be in an unnamed namespace, like `IsNewline` is.

An example file for the language should be added in `test/examples/asciidoc`. This enables automatic testing as described in `test/README` and also helps maintainers that are unfamiliar with the language. For an example with a similar lexer, examine `test/examples/markdown/AllStyles.md`

**Comment by ancebfer** [comment]
Two commits pushed following your recommendations.

**Comment by nyamatongwe** [comment]
Squashed into a single commit 3202e9e00c21cdeb99691c47c37026162e721077 along with change log entry.

**Comment by nyamatongwe** [comment]
Included in Lexilla 5.1.4

**Comment by georgeraraujo** [comment]
Hi,
I just tried this on SciTE 5.2.2 and it works GREAT! Please consider including `asciidoc.properties` in SciTE's full downloads.

**Comment by nyamatongwe** [comment]
@georgeraraujo, added `asciidoc.properties` to SciTE build but with it disabled by default, as is normal for new languages. Change `imports.exclude` in user properties to enable it.
https://sourceforge.net/p/scintilla/scite/ci/a55fa31d62562b55c705beb0dc8228d983388101/

**Pull request closed without merging**
