### PR TITLE
Use c++17 fallthrough attribute

### LINKED ISSUE #143: Switch fallthrough attribute
I am testing [C5262](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5262?view=msvc-170) warning/error for Notepad++.

And sometimes I use command line to enable code analysis with that warning, which also enable it for both Lexilla and Scintilla projects.
Because I also sometimes build with warnings as error, the build will fail because Lexilla has few C5262 warnings. 

@nyamatongwe 
And since Lexilla use c++17, could it use `[[fallthrough]]` attribute, instead of comments?

### PR DESCRIPTION
**Pull request by ozone10**
fix #143

### CODE REVIEW

**Comment by nyamatongwe** [comment]
Fall through was addressed in 2017 with 2b3bf9115bc97cb416afaa99745282b859b0345b where the gcc `Falls through` comment convention was chosen in preference to the `[[fallthrough]]` attribute for both portability and safety.

Changing the code of multiple lexers may lead to new bugs, particularly when the author does not use or otherwise interact with particular lexers and is unlikely to experience problems. The benefits to appeasing linters is small and not worth the potential for regressions. Is the code better after these changes? Not to me: falling through is already documented.

The best thing to do is to suppress the warning.

**Comment by ozone10** [comment]
Doesn't both lexilla and scintilla require C++17 compiler. And the `[[fallthrough]]` attribute is C++17 feature.
from `README` 
`MSVC 2019.4, GCC 9.0, Clang 9.0, and Apple Clang 11.0 are known to work.`

and minimal from https://en.cppreference.com/w/cpp/compiler_support/17
`MSVC 2017, GCC 7, Clang 3.9`

**Comment by nyamatongwe** [comment]
Scintilla started requiring C++17 in 2018 (after 2b3bf9115bc97cb416afaa99745282b859b0345b) and C++17 support was incomplete in that era's compilers.

Even now, some features are missing from some compilers or won't run on older operating systems. `std::for_each(std::execution::par, ...)`, a C++17 feature, isn't available in Apple Clang and requires downloading Intel's TBB library for gcc.

**Comment by ozone10** [comment]
There is difference between support for C++17 core language features and support for C++17 library features.

Also lexilla is already using the `[[fallthrough]]` attribute.
https://github.com/ScintillaOrg/lexilla/blob/bee4b3cb43bbe3dde05a0dcbb2ac6a6c3a56d95e/lexers/LexRuby.cxx#L1958
https://github.com/ScintillaOrg/lexilla/blob/301243674f321838b80270c83e6b913684a6c6d2/lexers/LexTCL.cxx#L322

Even commit https://github.com/ScintillaOrg/lexilla/commit/dfefd92cb85f63d533ca6ec17be73777a01e3d02 is about fixing warning for MSVC

**Comment by nyamatongwe** [comment]
> Also lexilla is already using the [[fallthrough]] attribute.

Its fine for someone invested in a lexer to change that lexer including adding `[[fallthrough]]`.

It is not, however, sensible to make a *low value* change to a set of lexers when the change author has little connection to those lexers or exposure to bugs in those lexers.

**Comment by ozone10** [comment]
I agree that I have little connection to those lexers, but how does making use of `[[fallthrough]]` to make switch fall through more explicit expose lexers to bugs.

**Comment by nyamatongwe** [comment]
> how does making use of [[fallthrough]] to make switch fall through more explicit expose lexers to bugs

Everyone makes mistakes. Mistakes are more likely when making similar, supposedly simple, changes to multiple places.

**Comment by ozone10** [comment]
But aren't those changes almost same as in commit https://github.com/ScintillaOrg/lexilla/commit/dfefd92cb85f63d533ca6ec17be73777a01e3d02

here instead of replacing comments with `[[fallthrough]];` they are added below them.

**Comment by nyamatongwe** [comment]
> But aren't those changes

I don't see what is meant by 'those'. Did you mean 'these', that is, the pull request.

**Comment by ozone10** [comment]
Sorry autocorrection.
Yes changes in this PR.

**Comment by nyamatongwe** [comment]
This pull request contains similar code to other accepted changes.

I am not rejecting this pull request on the basis of its correctness but on the scope and context of its changes.

**Comment by zufuliu** [comment]
Old (2018) discussion for `[[fallthrough]]` attribute: https://sourceforge.net/p/scintilla/bugs/2008/.

**Comment by nyamatongwe** [comment]
Closing as rejected,

**Pull request closed without merging**
