### PR TITLE
Add gdscript support

### PR DESCRIPTION
**Pull request by Davidy22**
Adding support for the [Godot](https://github.com/godotengine/godot) engine's custom built scripting language.

Heavily borrowed from the python lexer because GDScript is heavily inspired by python.

[Godot's own parser for reference](https://github.com/godotengine/godot/blob/3.x/modules/gdscript/gdscript_parser.cpp), although I didn't use it as much because the python lexer was closer at hand

A quick and dirty sample file that I used to make sure things worked while I added what wasn't in python and removed what's not in gdscript:
image

All testing and writing done in [geany's copy of lexilla](https://github.com/geany/geany/tree/master/scintilla)

### CODE REVIEW

**Comment by nyamatongwe** [comment]
The code in LexPython that detects that a single line string isn't terminated before line end isn't present. The lexer reacts to SCE_P_STRINGEOL but never sets it. Thus the `" unclosed` example in AllStyles.gd doesn't work.

It appears that the test wasn't run as the `.styled` file has 'staticmethod' where the `.gd` example file has 'onready'.

The naming convention wants "fold.quotes.gdscript" to be "fold.gdscript.quotes" and "tab.timmy.whinge.level" to be something that starts with "lexer.gdscript.". LexPython was implemented before the naming convention so has some legacy names.

Some compiler warnings should be fixed, probably just by removing any mentions of `needEOLCheck` and `inContinuedString`:
~~~
../lexers/LexGDScript.cxx: In member function 'virtual void LexerGDScript::Lex(Sci_PositionU, Sci_Position, int, Scintilla::IDocument*)':
../lexers/LexGDScript.cxx:394:8: warning: variable 'needEOLCheck' set but not used [-Wunused-but-set-variable]
  394 |   bool needEOLCheck = false;
      |        ^~~~~~~~~~~~
../lexers/LexGDScript.cxx:372:7: warning: variable 'inContinuedString' set but not used [-Wunused-but-set-variable]
  372 |  bool inContinuedString = false;
      |       ^~~~~~~~~~~~~~~~~
~~~

The condition around line 637 should be copied from current LexPython to avoid cppcheck warnings:
~~~
lexilla\lexers\LexGDScript.cxx:637:16: warning: Condition 'lineNext<=docLines' is always true [knownConditionTrueFalse]
     (lineNext <= docLines && IsCommentLine(lineNext, styler)))) {
               ^
lexilla\lexers\LexGDScript.cxx:635:15: note: Assuming that condition 'lineNext<docLines' is not redundant
    (lineNext < docLines) &&
              ^
lexilla\lexers\LexGDScript.cxx:637:16: note: Condition 'lineNext<=docLines' is always true
     (lineNext <= docLines && IsCommentLine(lineNext, styler)))) {
               ^
~~~

**Comment by Davidy22** [comment]
Had some stuff to fix with the ctags portion of this too, but finally got around to dealing with these, pushed something for now

**Comment by nyamatongwe** [comment]
If you look on the 'actions' tab of Davidy22/lexilla, there are red X signs showing there are problems with these patches.
https://github.com/Davidy22/lexilla/actions
The actions can be opened up to see what went wrong.

The main issue is that the tests aren't succeeding. Inside SciTE.properties, 'var' should be added to the keywords so that line 37, declaring `identifier` will lex correctly.

The `AllStyles.gd.styled` and `AllStyles.gd.folded` files are stale: line 48 of `AllStyles.gd.styled` has `decorator` instead of `annotation` and there is no `var` on line 37 of `AllStyles.gd.folded`. After running `lexilla/scripts/RunTest.bat` (`lexilla/scripts/RunTest.sh` on UNIX) problems will produce `.new` files which can be compared to the original files so see what has changed. Where the changes are correct, rename the '.new' files to the original name and rerun `RunTest` to check that it is OK.

A minor issue can be seen in the "Build Lexilla" stage of the actions with an unused variable that can be removed.
~~~
..\lexers\LexGDScript.cxx(335): warning C4101: 'i': unreferenced local variable
~~~
Unfortunately, as this is just a warning, its not made very visible.

This lexer is currently using Python style names `SCE_P_*`. If this lexer will follow the Python lexer strongly then this may be OK. However, if it is likely to diverge in an incompatible way then it may be best to use separate style names now or to say that there will be a later divergence and to treat the lexer as 'provisional' until that happens.

**Comment by Davidy22** [comment]
Bumbled around for a good bit, but figured out how to pass tests after a while. Spent a little bit wondering why the make command as per readme didn't do anything until I actually read the error message and figured out I also needed scintilla, something about the recent lexilla seperation I've heard about I think. Was also stubbornly just trying to hand modify test case expected output files and have my editor's automatic trailing newline insertion make me wonder why I couldn't get tests to pass for a hot minute. Finally got the green check though.

One of the big points about GDScript design was heavy similarity to python, although there are some quirks to separate it some amount, like explicit variable declaration. They already didn't have some features, I deleted large chunks of code related to f strings, including that bit to do with unclosed strings that I missed. They're actually about to go into beta with Godot 4, with breaking changes to the language, and while most of it is keyword/name changes and additions that wouldn't really conflict with python syntax I notice they're also previewing their own lambda syntax which is completely different from python's. The currently unfinalized coming lambda syntax doesn't actually add anything that isn't accounted in any of the `SCE_P_*` names, like the rest of the godot 4 changes, but this might be a sign that they're willing to break from the mold more in the future and I can probably spend a little more time to just give it it's own section. Can do it right after I fix some memory leaks in my ctags counterpart to this lexer.

**Comment by nyamatongwe** [comment]
Committed as a provisional feature to allow for more changes. Minor additions to Xcode project file, change log, and Cppcheck suppressions.

**Comment by nyamatongwe** [comment]
Added some extra checks for Scintilla in makefiles 93232e0 and stated requirement for Scintilla in documentation 803c8c5.

**Comment by Davidy22** [comment]
Did the switch, then did some testing with some syntax edge cases and found that

```
if param2 <= 2:
    print((-20 %


3) / 5)
    else:
        print(1)
```

Does not fold correctly even though it's technically correct syntax. It's also a bit hideous but there's variations on this syntax that could get used normally so will need to fix

**Comment by rdipardo** [comment]
> Python also allows this terrible use of whitespace, so the folding will need to be fixed in both.

@Davidy22 , I'm probably misunderstanding you, but it looks like the problem with your example is the reduced indentation of the trailing `3) / 5)` part. (If indent level is what you mean by "whitespace," then just ignore me.)

Python's folding logic depends on indent level, so reducing the indent inside the `if` branch will make the lexer close the fold region too early (a new, separate fold region starts whenever the indent increases relative to the previous line):

gd_edge_case_SciTe_515

With SciTE, you can visually debug fold levels with options like these:

```properties
# ~/.SciTEUser.properties
fold.flags=64
line.margin.width=10
```

**Comment by Davidy22** [comment]
The issue is that it's actually legal syntax that will run in both gdscript and python, despite how it violates indentation expectations, but the folding fails to properly fold the full statement because it only looks at indentation level. Need to halt indentation checking when we're inside brackets () or we find a \ at the end of a line. Although, since this is an existing issue in the python parser this maybe should be split away from this PR into an issue to be addressed later.

**Comment by nyamatongwe** [comment]
Committed change to SCE_GD_ as 38b9a8546fc5fced6125ebbea73de8a7425a175a.

**Comment by Davidy22** [comment]
At this point I don't have anything else I can think of to change with the parser, and my commits are all merged so I guess I'll close this.

**Pull request closed without merging**
