### PR TITLE
Added GDScript Lexer support for `%` and `$` symbols consistent with Godot Engine

### LINKED ISSUE #145: GDScript Lexer does not support `$` and `%` symbols
In GDScript `$` and `%` should be highlighted separately, with something like SCE_GD_GETNODE. 

`$` https://docs.godotengine.org/en/stable/tutorials/scripting/nodes_and_scene_instances.html#syntactic-sugar
https://docs.godotengine.org/en/stable/tutorials/best_practices/scene_organization.html#how-to-build-relationships-effectively
https://docs.godotengine.org/en/stable/tutorials/best_practices/godot_interfaces.html#acquiring-object-references

`%` Unique nodes: https://docs.godotengine.org/en/stable/tutorials/scripting/scene_unique_nodes.html

Untitled
image

### PR DESCRIPTION
**Pull request by 3fTL**
Fixes #145 

Image uses notepad++ with those changes, appears to be consistent with Godot Engine

image

### CODE REVIEW

**Comment by nyamatongwe** [comment]
Changes should include test cases that exercise those changes. For this pull request, an example of `SCE_GD_GETNODE` should be added to `test/examples/gdscript/AllStyles.gd`. Then run `TestLexers` as described in `test/README` and check the result files for correctness before including them in the changes.

The 3rd column of `LexicalClass` is a list of tags that allows applications to assign a basic colour scheme or implement features like "search in class (identifier|comment|string)". The tags should be similar to other lexers unless there is a strong need for a new tag. `getnode` isn't used by other lexers and `identifier` is more likely to be understood. The last column is an explanation that may appear in a style definition dialog.

For `%`, maybe only transition to the new style when the next character is alphabetic.

**Comment by nyamatongwe** [comment]
> Should SCE_GD_GETNODE be renamed to SCE_GD_NODE_IDENTIFIER?

I hadn't read the documentation before and it calls the bit after `$` 'the name or path of the node'. These are more like access paths into a database. Swift has `\` key-path expressions which can specify relative access for actions like sorting `items.sorted(by: \.owner.name)` although `SCE_GD_GETNODE` are absolute. It appears that `/` is allowed in `SCE_GD_GETNODE` and `/` could also be a division so may be ambiguous.

`SCE_GD_GETNODE` has multiple 'words' (possibly identifiers) separated by joining operators like `/`. It may deserve a new type called something like `path` if its going to be treated as one thing.

**Comment by nyamatongwe** [comment]
> so far i've renamed SCE_GD_GETNODE to SCE_GD_NODE_IDENTIFIER, should it be renamed to SCE_GD_NODEPATH?

`SCE_GD_NODEPATH` sounds reasonable to me. The tags entry should just be "path" until other path types are added to work out how they may need to be distinguished.

**Comment by nyamatongwe** [comment]
To be compatible with all Unicode characters, `StyleContext::ch` is an `int` so, to avoid potential truncation bugs, `GetGDStringState` should take an `int` argument.

**Comment by nyamatongwe** [comment]
Squashed and committed.

**Comment by nyamatongwe** [comment]
Included in version 5.2.4.

**Comment by kugel-** [comment]
I'm importing Lexilla 5.2.6 for Geany and I'm a little confused. The NodePath syntax merged here seems to be different from the Godot documentation (which uses `^"/root/Foo` ? See https://docs.godotengine.org/en/stable/classes/class_nodepath.html

What's correct now?

**Comment by kugel-** [comment]
I don't know Godot at all so I have to trust you on that. Will you open a follow-up PR?

Regarding `@`, words staring with that are mapped to annotations (whatever that exactly is). Is that only true for Godot 4? How look annotations in Godot 3 look like?

Do we even support multiple language versions or just 4?

**Pull request closed without merging**
